codecov:
  require_ci_to_pass: yes
  token: # Not required with OIDC

github_checks:
  annotations: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
        if_not_found: success
        only_pulls: false
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
        if_not_found: success

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  after_n_builds: 1

ignore:
  - "tests/"
  - "benchmarks/"
  - "docs/"
  - "setup.py"
  - "build.rs"
  - "**/__pycache__/"
  - "**/target/"

flags:
  unittests:
    paths:
      - src/python/teehistorian_py/
    carryforward: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
