use pyo3::prelude::*;
use pyo3::types::PyBytes;
use serde_json::{Value, json};
use uuid::Uuid;

use crate::errors::TeehistorianParseError;
use crate::registry;

/// Teehistorian file writer
///
/// This struct provides functionality to create valid teehistorian files
/// in a Pythonic way by accepting file-like objects and chunk objects.
///
/// # Teehistorian Format Specification
///
/// A valid teehistorian file consists of:
///
/// 1. **UUID Header (16 bytes)**: The fixed UUID `699db17b-8efb-34ff-b1d8-da6f60c15dd1`
///    in big-endian binary format. This identifies the file as a teehistorian.
///
/// 2. **JSON Header (null-terminated string)**: A JSON object containing metadata such as:
///    - `version`: "1" or "2" (required)
///    - `version_minor`: Minor version number (e.g., "9")
///    - `comment`: Comment about the recording
///    - `game_uuid`: UUID of the game session
///    - `prev_game_uuid`: Previous game session UUID
///    - `server_version`: Server version string
///    - `server_name`: Server name
///    - `start_time`: ISO 8601 timestamp
///    - `map_name`: Name of the map
///    - `map_sha256`: SHA256 hash of the map
///    - Other optional fields
///
/// 3. **Null Terminator (1 byte)**: A single 0x00 byte terminating the JSON header.
///
/// 4. **Message Stream**: Variable-width encoded messages following the teehistorian
///    message format (PLAYER_DIFF, INPUT_DIFF, DROP, JOIN, etc.)
///
/// # Important Notes
///
/// - The header is written using proper JSON encoding to ensure compatibility
/// - All messages are properly serialized using teehistorian's variable-width encoding
/// - The library automatically handles header writing when the first chunk is written
/// - String values in headers are preserved as strings (e.g., "map_size": "299932")
///
/// # Example
///
/// ```python
/// import teehistorian_py as th
///
/// # Create a new writer
/// writer = th.create()
///
/// # Optional: customize headers
/// writer.set_header("server_name", "My Custom Server")
/// writer.set_header("comment", "Generated by teehistorian-py")
///
/// # Write chunks
/// writer.write(th.Join(0))
/// writer.write(th.PlayerName(0, "Player Name"))
/// writer.write(th.PlayerDiff(0, 10, 5))
/// writer.write(th.Eos())
///
/// # Save to file
/// writer.save("output.teehistorian")
/// ```
#[pyclass(name = "TeehistorianWriter", module = "teehistorian_py")]
pub struct PyTeehistorianWriter {
    buffer: Vec<u8>,
    header_written: bool,
    header_data: Value,
    include_custom_chunk_metadata: bool,
}

#[pymethods]
impl PyTeehistorianWriter {
    /// Create a new teehistorian writer
    ///
    /// # Arguments
    /// * `file` - Optional file-like object to write to
    ///
    /// # Example
    /// ```python
    /// # Write to memory
    /// writer = th.TeehistorianWriter()
    ///
    /// # Write to file
    /// with open("output.teehistorian", "wb") as f:
    ///     writer = th.TeehistorianWriter(f)
    /// ```
    #[new]
    #[pyo3(signature = (_file = None))]
    fn new(_file: Option<&Bound<'_, PyAny>>) -> Self {
        let default_header = json!({
            "version": "2",
            "version_minor": "9",
            "comment": "teehistorian-py",
            "game_uuid": Uuid::nil().to_string(),
            "prev_game_uuid": Uuid::nil().to_string(),
            "server_version": "teehistorian-py 2.0.0",
            "server_name": "teehistorian-py Server"
        });

        Self {
            buffer: Vec::new(),
            header_written: false,
            header_data: default_header,
            include_custom_chunk_metadata: false,
        }
    }

    /// Write a chunk to the teehistorian
    ///
    /// # Arguments
    /// * `chunk` - A chunk object (Join, Drop, PlayerNew, etc.)
    ///
    /// # Example
    /// ```python
    /// writer = th.TeehistorianWriter()
    /// writer.write(th.Join(0))
    /// writer.write(th.PlayerName(0, "Player"))
    /// writer.write(th.Drop(0, "quit"))
    /// writer.write(th.Eos())
    /// ```
    fn write(&mut self, _py: Python<'_>, chunk: &Bound<'_, PyAny>) -> PyResult<()> {
        // Ensure header is written first
        if !self.header_written {
            self.write_header()?;
        }

        // Get the serialized data from the chunk
        let py_bytes = chunk.call_method0("write_to_buffer")?;
        let chunk_data: Vec<u8> = py_bytes.extract()?;

        // Append to our buffer
        self.buffer.extend_from_slice(&chunk_data);

        Ok(())
    }

    /// Write multiple chunks at once
    ///
    /// # Arguments
    /// * `chunks` - List of chunk objects
    ///
    /// # Example
    /// ```python
    /// writer = th.TeehistorianWriter()
    /// writer.write_all([
    ///     th.Join(0),
    ///     th.PlayerName(0, "Player"),
    ///     th.Eos()
    /// ])
    /// ```
    fn write_all(&mut self, py: Python<'_>, chunks: Vec<Py<PyAny>>) -> PyResult<()> {
        for chunk in chunks {
            self.write(py, chunk.bind(py))?;
        }
        Ok(())
    }

    /// Set header field value
    ///
    /// # Arguments
    /// * `key` - Header field name
    /// * `value` - Header field value (string)
    ///
    /// # Note
    /// Only JSON objects and arrays (strings starting with { or [) are parsed as JSON.
    /// All other values are stored as strings. This preserves string types for fields
    /// like "map_size": "299932" and prevents numeric strings from being converted to
    /// JSON numbers.
    ///
    /// # Example
    /// ```python
    /// import json
    /// writer.set_header("server_name", "My Custom Server")
    /// writer.set_header("comment", "Generated by my script")
    /// writer.set_header("map_size", "299932")  # Stored as string, not number
    /// # JSON objects/arrays are automatically parsed
    /// writer.set_header("config", json.dumps({"sv_motd": "Welcome"}))
    /// ```
    fn set_header(&mut self, key: String, value: String) -> PyResult<()> {
        if self.header_written {
            return Err(TeehistorianParseError::Validation(
                "Cannot modify header after writing has started".to_string(),
            )
            .into());
        }

        // Only parse JSON objects and arrays, not plain values
        // This preserves string types for fields like "map_size": "299932"
        let json_value = if (value.starts_with('{') && value.ends_with('}'))
            || (value.starts_with('[') && value.ends_with(']'))
        {
            // Try to parse as JSON object/array
            match serde_json::from_str::<Value>(&value) {
                Ok(v) => v,
                Err(_) => Value::String(value), // If parsing fails, store as string
            }
        } else {
            // Store all other values as strings
            Value::String(value)
        };

        self.header_data[key] = json_value;
        Ok(())
    }

    /// Get header field value
    ///
    /// # Arguments
    /// * `key` - Header field name
    ///
    /// # Returns
    /// Header field value or None if not set
    fn get_header(&self, key: String) -> Option<String> {
        self.header_data
            .get(&key)
            .and_then(|v| v.as_str())
            .map(|s| s.to_string())
    }

    /// Update multiple header fields from a dictionary
    ///
    /// # Arguments
    /// * `headers` - Dictionary of field names and values
    ///
    /// # Note
    /// Like set_header, only JSON objects/arrays are parsed.
    /// This allows you to set complex header structures in a single call.
    ///
    /// # Example
    /// ```python
    /// import json
    /// writer.update_headers({
    ///     "server_name": "My Server",
    ///     "comment": "Custom teehistorian file",
    ///     "config": json.dumps({"sv_motd": "Welcome", "sv_name": "My Server"})
    /// })
    /// ```
    fn update_headers(
        &mut self,
        _py: Python<'_>,
        headers: &Bound<'_, pyo3::types::PyDict>,
    ) -> PyResult<()> {
        if self.header_written {
            return Err(TeehistorianParseError::Validation(
                "Cannot modify header after writing has started".to_string(),
            )
            .into());
        }

        for (key, value) in headers.iter() {
            let key_str = key.extract::<String>()?;
            let value_str = value.extract::<String>()?;

            // Only parse JSON objects and arrays
            let json_value = if (value_str.starts_with('{') && value_str.ends_with('}'))
                || (value_str.starts_with('[') && value_str.ends_with(']'))
            {
                match serde_json::from_str::<Value>(&value_str) {
                    Ok(v) => v,
                    Err(_) => Value::String(value_str),
                }
            } else {
                Value::String(value_str)
            };

            self.header_data[key_str] = json_value;
        }

        Ok(())
    }

    /// Get all current data as bytes
    ///
    /// # Returns
    /// All written data as bytes
    ///
    /// # Example
    /// ```python
    /// writer = th.TeehistorianWriter()
    /// writer.write(th.Join(0))
    /// writer.write(th.Eos())
    /// data = writer.getvalue()  # Like BytesIO.getvalue()
    /// ```
    fn getvalue(&mut self, py: Python<'_>) -> PyResult<Py<PyAny>> {
        // Ensure header is written
        if !self.header_written {
            self.write_header()?;
        }

        Ok(PyBytes::new(py, &self.buffer).into())
    }

    /// Save to file path
    ///
    /// # Arguments
    /// * `path` - File path to save to
    ///
    /// # Example
    /// ```python
    /// writer = th.TeehistorianWriter()
    /// writer.write(th.Join(0))
    /// writer.write(th.Eos())
    /// writer.save("output.teehistorian")
    /// ```
    fn save(&mut self, path: String) -> PyResult<()> {
        // Ensure header is written
        if !self.header_written {
            self.write_header()?;
        }

        std::fs::write(&path, &self.buffer).map_err(|e| {
            TeehistorianParseError::File(format!("Failed to save to {}: {}", path, e))
        })?;
        Ok(())
    }

    /// Write all data to a file-like object
    ///
    /// # Arguments
    /// * `file` - File-like object with write() method
    ///
    /// # Example
    /// ```python
    /// writer = th.TeehistorianWriter()
    /// writer.write(th.Join(0))
    /// writer.write(th.Eos())
    ///
    /// with open("output.teehistorian", "wb") as f:
    ///     writer.writeto(f)
    /// ```
    fn writeto(&mut self, py: Python<'_>, file: &Bound<'_, PyAny>) -> PyResult<()> {
        // Ensure header is written
        if !self.header_written {
            self.write_header()?;
        }

        // Write to file-like object
        let data = PyBytes::new(py, &self.buffer);
        file.call_method1("write", (data,))?;

        Ok(())
    }

    /// Get current buffer size
    fn size(&self) -> usize {
        self.buffer.len()
    }

    /// Reset the writer to initial state
    fn reset(&mut self) {
        self.buffer.clear();
        self.header_written = false;

        // Reset to default header
        self.header_data = json!({
            "version": "2",
            "version_minor": "9",
            "comment": "teehistorian-py",
            "game_uuid": Uuid::nil().to_string(),
            "prev_game_uuid": Uuid::nil().to_string(),
            "server_version": "teehistorian-py 2.0.0",
            "server_name": "teehistorian-py Server"
        });
    }

    /// Check if any data has been written
    fn is_empty(&self) -> bool {
        self.buffer.is_empty() && !self.header_written
    }

    /// Context manager support
    fn __enter__(slf: Py<Self>) -> Py<Self> {
        slf
    }

    /// Context manager exit - ensures EOS is written if not already present
    fn __exit__(
        &mut self,
        _py: Python<'_>,
        _exc_type: Option<&Bound<'_, pyo3::types::PyAny>>,
        _exc_value: Option<&Bound<'_, pyo3::types::PyAny>>,
        _traceback: Option<&Bound<'_, pyo3::types::PyAny>>,
    ) -> PyResult<bool> {
        // For safety, we don't auto-write chunks in __exit__
        Ok(false)
    }

    /// String representation
    fn __repr__(&self) -> String {
        let status = if self.header_written {
            "started"
        } else {
            "empty"
        };
        format!(
            "TeehistorianWriter(size={}, status={})",
            self.buffer.len(),
            status
        )
    }

    /// Enable or disable custom chunk metadata in header
    ///
    /// When enabled, the writer will include __teehistorian_py metadata in the header
    /// with information about registered custom chunks.
    ///
    /// # Arguments
    /// * `enabled` - Whether to include metadata (default: false)
    ///
    /// # Example
    /// ```python
    /// writer = th.TeehistorianWriter()
    /// writer.set_include_custom_chunk_metadata(True)
    /// ```
    fn set_include_custom_chunk_metadata(&mut self, enabled: bool) -> PyResult<()> {
        if self.header_written {
            return Err(TeehistorianParseError::Validation(
                "Cannot modify metadata setting after writing has started".to_string(),
            )
            .into());
        }
        self.include_custom_chunk_metadata = enabled;
        Ok(())
    }
}

impl PyTeehistorianWriter {
    /// Write the header to the buffer in teehistorian format
    ///
    /// This method writes a valid teehistorian file header according to the specification:
    /// https://github.com/ddnet/ddnet/blob/master/TEEHISTORIAN.md
    ///
    /// The header consists of:
    /// 1. UUID (699db17b-8efb-34ff-b1d8-da6f60c15dd1) in big-endian binary format (16 bytes)
    /// 2. JSON header string containing metadata (variable length)
    /// 3. Null terminator (1 byte)
    ///
    /// The header is written in proper JSON format to ensure compatibility with all
    /// teehistorian parsers. String values are preserved as strings (not converted to numbers).
    ///
    /// After the header is written, chunks can be appended directly.
    fn write_header(&mut self) -> PyResult<()> {
        if self.header_written {
            return Ok(());
        }

        // Add __teehistorian_py metadata with registered custom chunks
        self.populate_custom_chunk_metadata();

        // The teehistorian UUID: 699db17b-8efb-34ff-b1d8-da6f60c15dd1
        // This is a version 3 UUID derived from the Teeworlds namespace
        // (e05ddaaa-c4e6-4cfb-b642-5d48e80c0029) and the name "teehistorian@ddnet.tw"
        let uuid_bytes: [u8; 16] = [
            0x69, 0x9d, 0xb1, 0x7b, 0x8e, 0xfb, 0x34, 0xff, 0xb1, 0xd8, 0xda, 0x6f, 0x60, 0xc1,
            0x5d, 0xd1,
        ];

        // Serialize the header data to JSON string
        let header_str = serde_json::to_string(&self.header_data).map_err(|e| {
            TeehistorianParseError::Write(format!("Failed to serialize header: {}", e))
        })?;

        // Step 1: Write the fixed UUID (16 bytes)
        self.buffer.extend_from_slice(&uuid_bytes);

        // Step 2: Write the JSON header string
        self.buffer.extend_from_slice(header_str.as_bytes());

        // Step 3: Write the null terminator
        self.buffer.push(0);

        self.header_written = true;

        Ok(())
    }

    /// Populate __teehistorian_py metadata with registered custom chunks
    fn populate_custom_chunk_metadata(&mut self) {
        // Only include metadata if enabled
        if !self.include_custom_chunk_metadata {
            return;
        }

        // Get all globally registered chunks
        let registered_uuids = registry::list_global();

        if registered_uuids.is_empty() {
            // No custom chunks, don't add metadata
            return;
        }

        let mut chunks_meta = serde_json::Map::new();

        for uuid in registered_uuids {
            if let Some(chunk_def) = registry::get_global(&uuid) {
                let mut chunk_obj = serde_json::Map::new();
                chunk_obj.insert("name".to_string(), json!(chunk_def.name));

                // Add field specifications
                let mut fields_obj = serde_json::Map::new();
                for field in chunk_def.fields {
                    let mut field_obj = serde_json::Map::new();

                    // Determine type from format
                    let type_str = match field.format {
                        registry::FieldFormat::Varint
                        | registry::FieldFormat::I8
                        | registry::FieldFormat::I16
                        | registry::FieldFormat::I32
                        | registry::FieldFormat::I64 => "i32",
                        registry::FieldFormat::String => "str",
                        registry::FieldFormat::Bytes => "bytes",
                        registry::FieldFormat::Uuid => "uuid",
                    };

                    let format_str = format!("{:?}", field.format);

                    field_obj.insert("type".to_string(), json!(type_str));
                    field_obj.insert("format".to_string(), json!(format_str));

                    fields_obj.insert(field.name, Value::Object(field_obj));
                }

                chunk_obj.insert("fields".to_string(), Value::Object(fields_obj));
                chunks_meta.insert(uuid, Value::Object(chunk_obj));
            }
        }

        // Only add __teehistorian_py if there are custom chunks
        if !chunks_meta.is_empty() {
            let mut teehistorian_py_meta = serde_json::Map::new();
            teehistorian_py_meta.insert("version".to_string(), json!("0.1.0"));
            teehistorian_py_meta.insert("chunks".to_string(), Value::Object(chunks_meta));

            self.header_data["__teehistorian_py"] = Value::Object(teehistorian_py_meta);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_writer_creation() {
        let writer = PyTeehistorianWriter::new(None);
        assert!(!writer.header_written);
        assert!(writer.buffer.is_empty());
        assert!(writer.is_empty());
    }

    #[test]
    fn test_header_operations() {
        let mut writer = PyTeehistorianWriter::new(None);

        // Test setting and getting header fields
        writer
            .set_header("test_key".to_string(), "test_value".to_string())
            .unwrap();
        assert_eq!(
            writer.get_header("test_key".to_string()),
            Some("test_value".to_string())
        );

        // Test getting non-existent field
        assert_eq!(writer.get_header("non_existent".to_string()), None);
    }

    #[test]
    fn test_reset() {
        let mut writer = PyTeehistorianWriter::new(None);
        writer.write_header().unwrap();
        assert!(!writer.is_empty());

        writer.reset();
        assert!(writer.is_empty());
        assert!(!writer.header_written);
    }

    #[test]
    fn test_json_header_parsing() {
        let mut writer = PyTeehistorianWriter::new(None);

        // Test that JSON strings are parsed correctly
        let json_config = r#"{"sv_motd":"Test","sv_name":"Server"}"#;
        writer
            .set_header("config".to_string(), json_config.to_string())
            .unwrap();

        // Verify that config is stored as a JSON object, not a string
        assert!(writer.header_data["config"].is_object());
        assert_eq!(
            writer.header_data["config"]["sv_motd"].as_str(),
            Some("Test")
        );
    }

    #[test]
    fn test_plain_string_header() {
        let mut writer = PyTeehistorianWriter::new(None);

        // Test that plain strings are stored as strings
        writer
            .set_header("comment".to_string(), "My comment".to_string())
            .unwrap();

        // Verify that comment is stored as a string
        assert!(writer.header_data["comment"].is_string());
        assert_eq!(writer.header_data["comment"].as_str(), Some("My comment"));
    }

    #[test]
    fn test_numeric_string_preservation() {
        let mut writer = PyTeehistorianWriter::new(None);

        // Test that numeric strings are preserved as strings, not converted to numbers
        writer
            .set_header("map_size".to_string(), "299932".to_string())
            .unwrap();

        // Verify that map_size is stored as a string
        assert!(writer.header_data["map_size"].is_string());
        assert_eq!(writer.header_data["map_size"].as_str(), Some("299932"));
    }

    #[test]
    fn test_json_object_parsing() {
        let mut writer = PyTeehistorianWriter::new(None);

        // Test that JSON objects are still parsed correctly
        let config_json = r#"{"sv_motd":"Welcome"}"#;
        writer
            .set_header("config".to_string(), config_json.to_string())
            .unwrap();

        // Verify that config is stored as an object
        assert!(writer.header_data["config"].is_object());
        assert_eq!(
            writer.header_data["config"]["sv_motd"].as_str(),
            Some("Welcome")
        );
    }
}
